GMAIL_ADDRESS: "smtp.gmail.com"
GMAIL_DOMAIN: "gmail.com"
GMAIL_USERNAME: "clubesocieto@gmail.com"
GMAIL_PASSWORD: "socie659"
EMAIL_PAGSEGURO: "cristiano.souza.mendonca@gmail.com"
TOKEN_PAGSEGURO: "F44DDEBEFA974444A6F49907B61FC878"
#TOKEN_PAGSEGURO: "E3F9F0BF27CA47AA9BCD6F7F15C64063"
PUBLIC_KEY_RECAPTCHA: '6Lc2TvUSAAAAAD6TEXAtmXQg4mKeljSZV_iexkyA'
PRIVATE_KEY_RECAPTCHA: '6Lc2TvUSAAAAALQoFLKos9ppwlfnndWueIls7mTM'
SECRET_KEY_BASE: "f4d100fa5284fd1631cbaa7621198662134eb137988b31420e1d1bb2dd8aaa858ef99bf20e958bb4415dc77b1bfb0372c5848b8de6d6895db83875a72aed83c0"