GMAIL_ADDRESS: "smtp.gmail.com"
GMAIL_DOMAIN: "gmail.com"
GMAIL_USERNAME: "email@example.com"
GMAIL_PASSWORD: "password"
EMAIL_PAGSEGURO: "email@example.com"
TOKEN_PAGSEGURO: "seu token"

#NÃO ALTERAR AS INFORMAÇÕES ABAIXO
PUBLIC_KEY_RECAPTCHA: '6Lc2TvUSAAAAAD6TEXAtmXQg4mKeljSZV_iexkyA'
PRIVATE_KEY_RECAPTCHA: '6Lc2TvUSAAAAALQoFLKos9ppwlfnndWueIls7mTM'
SECRET_KEY_BASE: "f4d100fa5284fd1631cbaa7621198662134eb137988b31420e1d1bb2dd8aaa858ef99bf20e958bb4415dc77b1bfb0372c5848b8de6d6895db83875a72aed83c0"